name: Angular Workflow
on: workflow_dispatch
#jobs:
#  build-application:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Print Welcome
#        run: echo "Hello World!!"
#      - name: Print discussion
#        run: |
#              echo "How is weather today?"
#              echo "It is too hot over here."
#      - name: Print Good bye
#        run: echo "Bye Bye World!!"

env:
  NODE_VERSION: '20.9.0'
  DIST_FOLDER: 'AngularActions/dist/angular-actions'

defaults:
  run:
    working-directory: AngularActions

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.upload-artifact.outputs.artifact-path || 'dist' }}
    steps:
      # - name: list all the files
      #   run: echo "files >>>> "
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Use Node.js v ${{env.NODE_VERSION}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      # - name: Cache npm
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #         ${{ runner.os }}-node-
          
      - name: Install npm Packages
        run: npm ci

      # - name: Run Unit Tests
      #   run: npm test --if-present -- --watch=false --browsers=chromeHeadless
      #   env:
      #     CI: true
      - name: Build Application
        run: npm run build

      - name: Upload build artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with: 
          name: angular-dist
          path: |
            ${{ env.DIST_FOLDER }}
          retention-days: 7
  
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download Artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: angular-dist
  #         path: ./dist
          
  #     - name: Deploy to Azure Web App (via publish profile)
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         package: ./dist/<project-name>









        
